### ISSUE TITLE
Create "Atlanta equity report" repo

### ISSUE THREAD

**Issue by Shaunm44** [CivicTechAtlanta/Atlanta-equity-report#1]
Maybe it's not as much an "equity" report first as much as it's a demographic snapshot to understand who Atlanta is. 

The desired outcome is that by collecting various data sources combined with a compelling narrative, we can paint a picture of who makes up Atlanta. This will be a useful reference for future projects to see who we should be including while we are building.

**Comment by ModelEarth** [comment]
Mark and Carolyn are currently updating our census by zip report Python pipeline to include All The Places location data.

We're looking for data visualization volunteers interested in showing changes across time using the census zip code data  from the static files we generate here:

https://model.earth/zip/io/

https://github.com/modelearth/zip

We could embed with a color choropleth map in an annual Atlanta community snapshot.
Would also be cool to include the NPU boundaries and local reps as hover links.

**Comment by Shaunm44** [comment]
@ModelEarth, it'd be great to discuss this more and see if there's opportunity to collaborate on something like an Equity Report.

I don't have the capacity to pick this project up just yet, but seems like a few pieces are coming together.
